### ISSUE TITLE
Choix de la techno

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-website#1]
- [x] Choix de la techno

- [ ] Push la structure de Base sur le git

**Comment by adriens** [comment]
Je propose donc de partir sur le GO avec https://gohugo.io/

Le GO est très prometteur
Antonin est fan aussi. C'est très intéressant.

On pourra faire de la CI dessus et avcner sur les GH Actions et promouvoir notre écisystème de manière très très propre et DevOps.

**Comment by adriens** [comment]
Je vais bosser sur le sujet des repos et indus j'espere ce jour
