### ISSUE TITLE
Chat communautaire

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-website#11]
Je vais devoir en mettre un canal de chat pour pouvoir avoir du feedback de la communauté

J'hésite entre :

- Slack
- Gitter
- Autre idée ?

**Comment by zYmMiJ** [comment]
Slack me parait bien.

**Comment by adriens** [comment]
On va commencer par tweeter avec un BOT pour faire vivre le contenu
je monte le slack apres

**Comment by adriens** [comment]
https://emploi-nc.slack.com

👍

**Comment by adriens** [comment]
Link fait avec Github
