### ISSUE TITLE
Onglet "Made with"

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-website#19]
Dans une endroit dédié, lister les outils et la stack, je pense que ça peut être itéressant
Prévoir une section d'intro, que je compléterai
Puis une liste à bullets:

- Slack
- Gthub
- Heroku
- RapiAPI
- Jitpack
- Spring Boot
- Flutter
- HUGO
- Krita (logo design)
- Sonic Pi
- autres...

**Comment by adriens** [comment]
je le mets en prio 1️⃣  comme ça je pourrai compléter a liste par la suite. Un premier jet jusque avec uneoudeux items sera pafait.
Cet onglet est inmportant car peut attirer des gens désireux de déveloopper des compétences autour de ces softs

**Comment by zYmMiJ** [comment]
@adriens J'ai esseyé plusieurs layouts, mais au final j'ai garder un truc simple. Dit moi si ca convient ?

**Comment by zYmMiJ** [comment]
Les icons sont clickables je les rediriges vers les docs ou vers nos liens à nous pour le slck github etc ?

**Comment by adriens** [comment]
Le layout est très bien.

Pour le nom de l'onglet, au lieu de mettre  Made , mettre "Stack" et c'est good.

Je retravaillerai le texte 👍
