### ISSUE TITLE
Implémenter le site dans github pages via la CI des Github Actions

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-website#4]

**Comment by adriens** [comment]
Ok, on processsera en CI le master et on poussera en continu sur le `gh-pages` de cette même repo.
On utilisera Github Actions via https://github.com/marketplace/actions/hugo-to-gh-pages

C'est parfait, je voulais justement que l'on s'y colle.

Ce sera élégant visuellement et techniquement. @zYmMiJ

**Comment by adriens** [comment]
✔️

**Comment by adriens** [comment]
Attention, avant de pousser faire #5 ⚠️

**Comment by zYmMiJ** [comment]
C'est noté

**Comment by adriens** [comment]
Voici le scret pour pusher sur `gh-pages` : `HUGO_DEPLOY_WEBSITE`

**Comment by adriens** [comment]
https://adriens.github.io/emploi-nc-website/
