### ISSUE TITLE
Faire une page/section A propos (disclaimer)

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-website#5]
Préparer une page A propos

Nous y préciserons:

- les conditions de dev
- le but de la démarche

Mets un texte minimaliste, je compléterai.

**Comment by zYmMiJ** [comment]
C'est noté

**Comment by adriens** [comment]
# Jitpack

- [ ] Rendre le logo clickable et envoyer sur https://jitpack.io/#adriens/emploi-nc-sdk
- [ ] Montrer le badge svg qui montre le num de version comme à la racine du projet du SDK

**Comment by adriens** [comment]
# API

- [ ] Rendre logo clickable et renvoyer sur https://rapidapi.com/adriens/api/emploi-nouvelle-caledonie

**Comment by adriens** [comment]
# Appli mobile

- [ ]  Embedder le player youtube qui pointe vers la chaîne youtube

**Comment by zYmMiJ** [comment]
C'est ok pour les logo clickable, et l'embed ytbe.
Peut-etre le placement du svg jitpack sous le logo ?
Je supprime les capture en dessous de l'embed ?

**Comment by adriens** [comment]
Déja comme ça c good, tentes les sv, on les debriefera ensembls pendant lepoint pre-release publique
